### ISSUE TITLE
Find Agent Exception

### ISSUE THREAD

**Issue by lintsai** [Infotrends-Info360/IMWebSocket#1]
Find Agent 時，Server會產生未收到JSON Target的狀況
![json](https://cloud.githubusercontent.com/assets/22093362/22133075/1133ea56-def9-11e6-814b-698a04bd20d8.PNG)
請在Server接收時，改成Select Key的方式，而非強制接收的方式

**Comment by lintsai** [comment]
@uopsdod 麻煩有時間時解決

**Comment by uopsdod** [comment]
已解決,將senduserdata順序改到找到Agent之後才觸發,即可避免空值問題
![ax4](https://cloud.githubusercontent.com/assets/19677817/22230669/e41986a6-e219-11e6-83f1-a47eaa706be8.png)
