### ISSUE TITLE
Leave Group Exception

### ISSUE THREAD

**Issue by lintsai** [Infotrends-Info360/IMWebSocket#2]
前端頁面離開時會產生找不到group的JSON Target
![leavegroup](https://cloud.githubusercontent.com/assets/22093362/22133309/81fa3690-defa-11e6-82d1-7e1269eb229e.PNG)
將讀取JSON Target的方式更改成Search Key的方式，而非強制讀取

**Comment by lintsai** [comment]
@uopsdod

**Comment by uopsdod** [comment]
已解決, 在整理onClose與heartBeat時也一併解決了,此例外狀況不再出現
![ax3](https://cloud.githubusercontent.com/assets/19677817/22230612/91d5cd0a-e219-11e6-95d8-d449a2cc9fd5.png)
