### ISSUE TITLE
完成前端Client/Agent版面

### ISSUE THREAD

**Issue by uopsdod** [Infotrends-Info360/IMWebSocket#25]
不使用layim

**Comment by Infotrends-Info360** [comment]
已完成
![acc8](https://cloud.githubusercontent.com/assets/25216070/23599692/8bf978f8-027d-11e7-99c7-3cb0fef1f555.png)
![acc9](https://cloud.githubusercontent.com/assets/25216070/23599694/8de8ea54-027d-11e7-90a6-422003b88fed.png)
