### ISSUE TITLE
Agent在ready - Accept期間若登出, 須通知client繼續找其他Agent

### ISSUE THREAD

**Issue by uopsdod** [Infotrends-Info360/IMWebSocket#26]

**Comment by Infotrends-Info360** [comment]
已完成
client.js
![acc5](https://cloud.githubusercontent.com/assets/25216070/23599611/26463ff0-027d-11e7-9012-208fb72d685c.png)


agent.js
![acc6](https://cloud.githubusercontent.com/assets/25216070/23599614/288a2ace-027d-11e7-990f-76cc05495d3c.png)
![acc7](https://cloud.githubusercontent.com/assets/25216070/23599617/2b2e40da-027d-11e7-8eba-ac219b98fc47.png)
