### ISSUE TITLE
HeartBeat and onClose

### ISSUE THREAD

**Issue by lintsai** [Infotrends-Info360/IMWebSocket#3]
HeartBeat偵測人員是否斷線的機制目前有問題，請測試看看甚麼方法可以在人員異常段線時，觸發onClose function
![onclose](https://cloud.githubusercontent.com/assets/22093362/22133553/e0ba48f4-defb-11e6-806e-e758b2d593a0.PNG)

**Comment by lintsai** [comment]
@uopsdod

**Comment by uopsdod** [comment]
已整理並精簡HeartBeat功能程式碼,增加可維護性與穩定度
於onClose()方法中新增兩private methods:
		inputInteractionLog(conn,reason);
		clearUserData(conn); // 包含removeUser, removerUserinTYPE, removeUseringroup
在使用者異常斷線、重整網頁或登出時,皆會由onClose做最後清理動作
![ax2](https://cloud.githubusercontent.com/assets/19677817/22230526/15c7b2e6-e219-11e6-9223-2859cbaf22df.png)
