### ISSUE TITLE
新增讓主管能夠設定 在iEstablished狀態後 是要notready還是要ready

### ISSUE THREAD

**Issue by uopsdod** [Infotrends-Info360/IMWebSocket#31]
- [ ] 建立全域變數

**Comment by Infotrends-Info360** [comment]
已完成
ws.java
![acc2](https://cloud.githubusercontent.com/assets/25216070/23599431/f692fb14-027b-11e7-9b5d-3239a923db15.png)

agent.js
![acc](https://cloud.githubusercontent.com/assets/25216070/23599434/fc54ded2-027b-11e7-9d94-2263e9628ee2.png)
