### ISSUE TITLE
interactionlog - 當Client F5重整時會失敗 - closefrom not found

### ISSUE THREAD

**Issue by Infotrends-Info360** [Infotrends-Info360/IMWebSocket#36]
![acacaca](https://cloud.githubusercontent.com/assets/25216070/23787153/a5fb5754-05ab-11e7-9b07-d03987d01634.png)

**Comment by uopsdod** [comment]
已解決
![adad1](https://cloud.githubusercontent.com/assets/19677817/23889133/73399b82-08c6-11e7-8566-f3d93d405494.png)
