### ISSUE TITLE
將maxCount機制移至Websocket Server

### ISSUE THREAD

**Issue by Infotrends-Info360** [Infotrends-Info360/IMWebSocket#37]
![adad](https://cloud.githubusercontent.com/assets/25216070/23889059/19a6932c-08c6-11e7-9d13-43c9714c9857.png)

**Comment by uopsdod** [comment]
已完成
![ccaca](https://cloud.githubusercontent.com/assets/19677817/24846263/c7f61fee-1deb-11e7-86c3-18750173f926.png)

![acacacaca](https://cloud.githubusercontent.com/assets/19677817/24846264/ca8c1e16-1deb-11e7-9e2d-a81ec20ebee6.png)
